# Generated by Django 3.0.3 on 2020-02-09 17:27

from django.db import migrations, models
import tasks.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('execution', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(default=tasks.models.generate_random_code, max_length=127, unique=True)),
                ('state', models.CharField(choices=[('scheduled', 'Scheduled Task'), ('executed', 'Executed Task'), ('missed', 'Missed Task')], default='scheduled', max_length=9)),
                ('scheduled', models.DateTimeField()),
                ('callback', models.URLField()),
            ],
        ),
    ]
